const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentPage='overview', listeners=[], editingName=null, logs=[], paused=false, eventSource=null, pollTimer=null;
const titles={overview:['总览','mihomo 实时运行状态'],listeners:['入站','管理 listeners 配置'],config:['配置','安全编辑、校验与备份'],logs:['日志','mihomo 实时结构化日志']};
async function api(path,options={}){const o={...options,headers:{...(options.headers||{})}};if(o.body&&!o.headers['Content-Type'])o.headers['Content-Type']='application/json';const res=await fetch(path,o);let data={};try{data=await res.json()}catch{}if(res.status===401){showLogin();throw new Error('会话已过期')}if(!res.ok)throw new Error(data.error||`请求失败 (${res.status})`);return data}
function busy(button,on){button.disabled=on;if(on){button.dataset.label=button.textContent;button.textContent='处理中…'}else if(button.dataset.label)button.textContent=button.dataset.label}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.add('hidden'),3200)}
function showLogin(){closeLogs();clearInterval(pollTimer);$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');navigate('overview')}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter,err=$('#login-error');err.classList.add('hidden');busy(b,true);try{const f=new FormData(e.target);await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});e.target.reset();showApp()}catch(x){err.textContent=x.message;err.classList.remove('hidden')}finally{busy(b,false)}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}finally{showLogin()}});
$$('nav button').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$('#menu-button').onclick=()=>$('#sidebar').classList.toggle('open');
function navigate(page){currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#page-title').textContent=titles[page][0];$('#page-subtitle').textContent=titles[page][1];$('#sidebar').classList.remove('open');closeLogs();if(page==='overview'){loadOverview();clearInterval(pollTimer);pollTimer=setInterval(loadOverview,2000)}else{clearInterval(pollTimer);if(page==='listeners')loadListeners();if(page==='config')loadConfig();if(page==='logs')openLogs()}}
const bytes=(n,rate=false)=>{if(n==null)return'--';const units=['B','KB','MB','GB','TB'];let i=0,v=Number(n);while(v>=1024&&i<4){v/=1024;i++}return `${v.toFixed(i?1:0)} ${units[i]}${rate?'/s':''}`};
async function loadOverview(){try{const d=await api('/api/overview');const online=!!d.online;$('#online').innerHTML=`<i class="dot ${online?'online':'offline'}"></i>${online?'在线':'离线'}`;$('#mobile-status').className=`dot ${online?'online':'offline'}`;$('#offline-banner').classList.toggle('hidden',online);$('#offline-message').textContent=d.message||'无法获取运行数据';$('#version').textContent=d.version||'--';$('#mode').textContent=d.mode||'--';[['upload',bytes(d.upload,true)],['download',bytes(d.download,true)],['total-upload',bytes(d.totalUpload)],['total-download',bytes(d.totalDownload)],['memory',bytes(d.memory)],['connections',online?String(d.connections):'--']].forEach(([id,v])=>$(`#${id}`).textContent=online?v:'--')}catch(e){$('#offline-banner').classList.remove('hidden');$('#offline-message').textContent=e.message}}
$$('[data-action]').forEach(b=>b.onclick=async()=>{const action=b.dataset.action;if(action!=='start'&&!await confirmAction(`确认${action==='stop'?'停止':'重启'} mihomo？`,'服务连接会短暂中断。'))return;busy(b,true);try{await api(`/api/service/${action}`,{method:'POST',body:'{}'});toast('服务操作已提交');setTimeout(loadOverview,800)}catch(e){toast(e.message,true)}finally{busy(b,false)}});
function confirmAction(title,text){return new Promise(resolve=>{const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;d.showModal();d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true})})}
async function loadListeners(){const body=$('#listener-body');body.innerHTML='<tr><td colspan="5">载入中…</td></tr>';try{const d=await api('/api/listeners');listeners=d.listeners||[];body.innerHTML='';$('#listener-count').textContent=`共 ${listeners.length} 个入站`;$('#listener-empty').classList.toggle('hidden',listeners.length>0);listeners.forEach(l=>{const tr=document.createElement('tr');tr.innerHTML=`<td></td><td></td><td></td><td></td><td><button class="edit">编辑</button> <button class="delete">删除</button></td>`;tr.children[0].textContent=l.name;tr.children[1].textContent=l.type;tr.children[2].textContent=l.listen;tr.children[3].textContent=l.port;tr.querySelector('.edit').onclick=()=>openListener(l);tr.querySelector('.delete').onclick=()=>deleteListener(l.name);body.append(tr)})}catch(e){body.innerHTML=`<tr><td colspan="5">${e.message}</td></tr>`}}
$('#add-listener').onclick=()=>openListener();function openListener(l=null){editingName=l?.name||null;$('#listener-dialog-title').textContent=l?'编辑入站':'新增入站';const f=$('#listener-form');f.reset();f.elements.listen.value=l?.listen||'0.0.0.0';if(l){['name','type','port','extraYaml'].forEach(k=>f.elements[k].value=l[k]??'')}$('#listener-error').classList.add('hidden');$('#listener-dialog').showModal()}$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#listener-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter,err=$('#listener-error'),raw=Object.fromEntries(new FormData(e.target));raw.port=Number(raw.port);busy(b,true);try{await api(editingName?`/api/listeners/${encodeURIComponent(editingName)}`:'/api/listeners',{method:editingName?'PUT':'POST',body:JSON.stringify(raw)});$('#listener-dialog').close();toast('入站配置已保存');loadListeners()}catch(x){err.textContent=x.message;err.classList.remove('hidden')}finally{busy(b,false)}};
async function deleteListener(name){if(!await confirmAction(`删除入站“${name}”？`,'保存后将立即重载 mihomo 配置。'))return;try{await api(`/api/listeners/${encodeURIComponent(name)}`,{method:'DELETE',body:'{}'});toast('入站已删除');loadListeners()}catch(e){toast(e.message,true)}}
async function loadConfig(){const editor=$('#config-editor');editor.disabled=true;editor.value='正在读取配置…';try{const d=await api('/api/config');editor.value=d.yaml}catch(e){editor.value='';toast(e.message,true)}finally{editor.disabled=false}loadBackups()}
$('#save-config').onclick=async function(){if(!await confirmAction('保存并热重载配置？','保存前会校验配置，并自动创建备份。'))return;busy(this,true);try{await api('/api/config',{method:'PUT',body:JSON.stringify({yaml:$('#config-editor').value})});toast('配置已保存并重载');loadBackups()}catch(e){toast(e.message,true)}finally{busy(this,false)}};
async function loadBackups(){const el=$('#backup-list');el.innerHTML='';try{const d=await api('/api/config/backups');(d.backups||[]).forEach(x=>{const row=document.createElement('div');row.className='backup-item';const label=document.createElement('span');label.textContent=`${new Date(x.createdAt).toLocaleString()} · ${bytes(x.size)}`;const b=document.createElement('button');b.textContent='恢复';b.onclick=()=>restoreBackup(x.id);row.append(label,b);el.append(row)})}catch(e){toast(e.message,true)}}$('#refresh-backups').onclick=loadBackups;
async function restoreBackup(id){if(!await confirmAction('恢复此备份？','当前配置也会先备份，校验成功后热重载。'))return;try{await api(`/api/config/backups/${encodeURIComponent(id)}/restore`,{method:'POST',body:'{}'});toast('备份已恢复');loadConfig()}catch(e){toast(e.message,true)}}
function openLogs(){logs=[];renderLogs();eventSource=new EventSource('/api/logs/stream');eventSource.onopen=()=>$('#log-state').textContent='实时连接';eventSource.onerror=()=>$('#log-state').textContent='连接中断，正在重连';eventSource.onmessage=e=>{try{const d=JSON.parse(e.data),level=(d.type||d.level||'info').toLowerCase(),message=d.payload||d.message||e.data;logs.push({time:new Date().toLocaleTimeString(),level,message});if(logs.length>300)logs.shift();if(!paused)renderLogs()}catch{}}}
function closeLogs(){if(eventSource){eventSource.close();eventSource=null}}function renderLogs(){const filter=$('#log-level').value,out=$('#log-output');out.innerHTML='';logs.filter(x=>filter==='all'||x.level===filter).forEach(x=>{const row=document.createElement('div');row.className='log-line';const t=document.createElement('span'),l=document.createElement('span'),m=document.createElement('span');t.textContent=x.time;l.textContent=x.level.toUpperCase();l.className=x.level;m.textContent=x.message;row.append(t,l,m);out.append(row)});out.scrollTop=out.scrollHeight}
$('#pause-logs').onclick=function(){paused=!paused;this.textContent=paused?'继续':'暂停';$('#log-state').textContent=paused?'已暂停显示':'实时连接';if(!paused)renderLogs()};$('#clear-logs').onclick=()=>{logs=[];renderLogs()};$('#log-level').onchange=renderLogs;
api('/api/auth/session').then(showApp).catch(showLogin);
