const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentPage='listeners', listeners=[], editingName=null, sharingName=null;
const titles={listeners:['入站','管理 listeners 配置'],config:['配置','安全编辑、校验与备份']};
async function api(path,options={}){const o={...options,headers:{...(options.headers||{})}};if(o.body&&!o.headers['Content-Type'])o.headers['Content-Type']='application/json';const res=await fetch(path,o);let data={};try{data=await res.json()}catch{}if(res.status===401){showLogin();throw new Error('会话已过期')}if(!res.ok)throw new Error(data.error||`请求失败 (${res.status})`);return data}
function busy(button,on){button.disabled=on;if(on){button.dataset.label=button.textContent;button.textContent='处理中…'}else if(button.dataset.label)button.textContent=button.dataset.label}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.add('hidden'),3200)}
function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');navigate('listeners')}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter,err=$('#login-error');err.classList.add('hidden');busy(b,true);try{const f=new FormData(e.target);await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});e.target.reset();showApp()}catch(x){err.textContent=x.message;err.classList.remove('hidden')}finally{busy(b,false)}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}finally{showLogin()}});
$$('nav button').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$('#menu-button').onclick=()=>$('#sidebar').classList.toggle('open');
function navigate(page){currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#page-title').textContent=titles[page][0];$('#page-subtitle').textContent=titles[page][1];$('#sidebar').classList.remove('open');if(page==='listeners')loadListeners();if(page==='config')loadConfig()}
const bytes=n=>{if(n==null)return'--';const units=['B','KB','MB','GB','TB'];let i=0,v=Number(n);while(v>=1024&&i<4){v/=1024;i++}return `${v.toFixed(i?1:0)} ${units[i]}`};
function confirmAction(title,text){return new Promise(resolve=>{const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;d.showModal();d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true})})}
async function loadListeners(){const body=$('#listener-body');body.innerHTML='<tr><td colspan="5">载入中…</td></tr>';try{const d=await api('/api/listeners');listeners=d.listeners||[];body.innerHTML='';$('#listener-count').textContent=`共 ${listeners.length} 个入站`;$('#listener-empty').classList.toggle('hidden',listeners.length>0);listeners.forEach(l=>{const tr=document.createElement('tr');tr.innerHTML=`<td></td><td></td><td></td><td></td><td><button class="share">分享</button> <button class="edit">编辑</button> <button class="delete">删除</button></td>`;tr.children[0].textContent=l.name;tr.children[1].textContent=l.type;tr.children[2].textContent=l.listen;tr.children[3].textContent=l.port;tr.querySelector('.share').onclick=()=>openShare(l);tr.querySelector('.edit').onclick=()=>openListener(l);tr.querySelector('.delete').onclick=()=>deleteListener(l.name);body.append(tr)})}catch(e){body.innerHTML=`<tr><td colspan="5">${e.message}</td></tr>`}}
$('#add-listener').onclick=()=>openListener();$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());function openListener(l=null){editingName=l?.name||null;$('#listener-dialog-title').textContent=l?'编辑入站':'新增入站';const f=$('#listener-form');f.reset();f.elements.listen.value=l?.listen||'0.0.0.0';if(l){['name','type','port','extraYaml'].forEach(k=>f.elements[k].value=l[k]??'')}$('#listener-error').classList.add('hidden');setupVlessForm(l);$('#listener-dialog').showModal()}function setupVlessForm(l){const f=$('#listener-form');const isVless=f.elements.type.value==='vless';$('#vless-section').classList.toggle('hidden',!isVless);if(!isVless){$('#vless-users').innerHTML='';return}const v=l?.vless||null;const users=(v&&Array.isArray(v.users)&&v.users.length)?v.users:[{}];renderVlessUsers(users);const r=v&&v.reality?v.reality:null;const enabled=!!r;const re=$('#reality-enabled');re.checked=enabled;re.dispatchEvent(new Event('change'));if(r){f.elements.realityDest.value=r.dest||'';f.elements.realityPrivateKey.value=r.privateKey||'';f.elements.realityShortIds.value=(r.shortIds||[]).join('\n');f.elements.realityServerNames.value=(r.serverNames||[]).join('\n');f.elements.realityExtraYaml.value=r.extraYaml||''}else{['realityDest','realityPrivateKey','realityShortIds','realityServerNames','realityExtraYaml'].forEach(k=>f.elements[k].value='')}}
function renderVlessUsers(users){const box=$('#vless-users');box.innerHTML='';users.forEach(u=>{const row=document.createElement('div');row.className='vless-user';if(u.extraYaml)row.dataset.extraYaml=u.extraYaml;const mk=(tag,cls,ph)=>{const el=document.createElement(tag);el.className=cls;el.placeholder=ph||'';return el};const un=mk('input','vuser-username','用户名');un.value=u.username||'';const ui=mk('input','vuser-uuid','UUID*');ui.value=u.uuid||'';const fl=mk('input','vuser-flow','flow');fl.value=u.flow||'';const del=document.createElement('button');del.type='button';del.className='mini danger';del.textContent='删除';del.onclick=()=>{row.remove()};row.append(un,ui,fl,del);box.append(row)})}
$('#add-vless-user').onclick=()=>renderVlessUsers([...$$('#vless-users .vless-user')].map(row=>({username:row.querySelector('.vuser-username').value,uuid:row.querySelector('.vuser-uuid').value,flow:row.querySelector('.vuser-flow').value,extraYaml:row.dataset.extraYaml||''})).concat([{}]));
$('#reality-enabled').addEventListener('change',e=>$('#reality-fields').classList.toggle('hidden',!e.target.checked));
$('#listener-form').elements.type.addEventListener('change',e=>{const isVless=e.target.value==='vless';$('#vless-section').classList.toggle('hidden',!isVless);if(isVless&&!$('#vless-users').children.length)renderVlessUsers([{}])});
function collectVless(validate){const rows=[...$$('#vless-users .vless-user')];const users=rows.map(row=>({username:row.querySelector('.vuser-username').value.trim(),uuid:row.querySelector('.vuser-uuid').value.trim(),flow:row.querySelector('.vuser-flow').value.trim(),extraYaml:row.dataset.extraYaml||''})).filter(u=>u.uuid||u.username||u.flow);if(validate){if(!users.length)throw new Error('至少需要一个有效用户');for(const u of users)if(!u.uuid)throw new Error('每个用户都必须填写 UUID')}const enabled=$('#reality-enabled').checked;const f=$('#listener-form');let reality=null;if(enabled){const dest=f.elements.realityDest.value.trim(),pk=f.elements.realityPrivateKey.value.trim();const shortIds=f.elements.realityShortIds.value.split('\n').map(x=>x.trim()).filter(Boolean);const serverNames=f.elements.realityServerNames.value.split('\n').map(x=>x.trim()).filter(Boolean);if(validate){if(!dest)throw new Error('Reality 必须填写 dest');if(!pk)throw new Error('Reality 必须填写 privateKey');if(!shortIds.length)throw new Error('Reality 至少需要一个 shortId');if(!serverNames.length)throw new Error('Reality 至少需要一个 serverName')}reality={dest,privateKey:pk,shortIds,serverNames,extraYaml:f.elements.realityExtraYaml.value}}return{vless:{users,reality}}}
$('#listener-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter,err=$('#listener-error'),f=e.target,raw=Object.fromEntries(new FormData(f));raw.port=Number(raw.port);['realityDest','realityPrivateKey','realityShortIds','realityServerNames','realityExtraYaml'].forEach(k=>delete raw[k]);if(f.elements.type.value==='vless'){try{Object.assign(raw,collectVless(true))}catch(ve){err.textContent=ve.message;err.classList.remove('hidden');return}}else{delete raw.vless}busy(b,true);try{await api(editingName?`/api/listeners/${encodeURIComponent(editingName)}`:'/api/listeners',{method:editingName?'PUT':'POST',body:JSON.stringify(raw)});$('#listener-dialog').close();toast('入站配置已保存');loadListeners()}catch(x){err.textContent=x.message;err.classList.remove('hidden')}finally{busy(b,false)}};
function openShare(l){sharingName=l.name;$('#share-name').textContent=`${l.name}（${l.type}）`;$('#share-host').value='';$('#share-list').innerHTML='';$('#share-error').classList.add('hidden');$('#share-loading').classList.add('hidden');$('#share-dialog').showModal()}
$('#share-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter,err=$('#share-error'),list=$('#share-list'),loading=$('#share-loading');const host=$('#share-host').value.trim();err.classList.add('hidden');list.innerHTML='';if(!host){err.textContent='请填写公网域名或 IP';err.classList.remove('hidden');return}busy(b,true);loading.classList.remove('hidden');try{const d=await api(`/api/listeners/${encodeURIComponent(sharingName)}/shares?host=${encodeURIComponent(host)}`);const shares=d.shares||[];loading.classList.add('hidden');if(!shares.length){const p=document.createElement('p');p.className='empty share-empty';p.textContent='该协议暂无通用分享链接';list.append(p);return}shares.forEach(s=>list.append(renderShare(s)))}catch(x){loading.classList.add('hidden');err.textContent=x.message;err.classList.remove('hidden')}finally{busy(b,false)}};
function renderShare(s){const item=document.createElement('div');item.className='share-item';const label=document.createElement('div');label.className='share-label';label.textContent=s.label;const uri=document.createElement('div');uri.className='share-uri';const uriText=document.createElement('input');uriText.type='text';uriText.readOnly=true;uriText.value=s.uri;const copy=document.createElement('button');copy.type='button';copy.className='mini';copy.textContent='复制';copy.onclick=()=>copyText(s.uri,copy);uri.append(uriText,copy);item.append(label,uri);if(typeof s.qrDataUrl==='string'&&s.qrDataUrl.startsWith('data:image/png;base64,')){const qr=document.createElement('img');qr.className='share-qr';qr.alt=`${s.label} 二维码`;qr.src=s.qrDataUrl;item.append(qr)}else{const bad=document.createElement('p');bad.className='message error share-qr-error';bad.textContent='二维码数据异常，已拒绝加载';item.append(bad)}return item}
function copyFeedback(btn,ok){const original=btn.textContent;btn.textContent=ok?'已复制':'复制失败';btn.disabled=ok;btn.classList.toggle('ok',ok);clearTimeout(btn._t);btn._t=setTimeout(()=>{btn.textContent=original;btn.disabled=false;btn.classList.remove('ok')},1600)}
async function copyText(text,btn){const fallback=()=>{const ta=document.createElement('textarea');ta.value=text;ta.className='offscreen';document.body.appendChild(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();copyFeedback(btn,ok)};try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);copyFeedback(btn,true)}else fallback()}catch{fallback()}}
async function deleteListener(name){if(!await confirmAction(`删除入站“${name}”？`,'保存后将立即重载 mihomo 配置。'))return;try{await api(`/api/listeners/${encodeURIComponent(name)}`,{method:'DELETE',body:'{}'});toast('入站已删除');loadListeners()}catch(e){toast(e.message,true)}}
async function loadConfig(){const editor=$('#config-editor');editor.disabled=true;editor.value='正在读取配置…';try{const d=await api('/api/config');editor.value=d.yaml}catch(e){editor.value='';toast(e.message,true)}finally{editor.disabled=false}loadBackups()}
$('#save-config').onclick=async function(){if(!await confirmAction('保存并热重载配置？','保存前会校验配置，并自动创建备份。'))return;busy(this,true);try{await api('/api/config',{method:'PUT',body:JSON.stringify({yaml:$('#config-editor').value})});toast('配置已保存并重载');loadBackups()}catch(e){toast(e.message,true)}finally{busy(this,false)}};
async function loadBackups(){const el=$('#backup-list');el.innerHTML='';try{const d=await api('/api/config/backups');(d.backups||[]).forEach(x=>{const row=document.createElement('div');row.className='backup-item';const label=document.createElement('span');label.textContent=`${new Date(x.createdAt).toLocaleString()} · ${bytes(x.size)}`;const b=document.createElement('button');b.textContent='恢复';b.onclick=()=>restoreBackup(x.id);row.append(label,b);el.append(row)})}catch(e){toast(e.message,true)}}$('#refresh-backups').onclick=loadBackups;
async function restoreBackup(id){if(!await confirmAction('恢复此备份？','当前配置也会先备份，校验成功后热重载。'))return;try{await api(`/api/config/backups/${encodeURIComponent(id)}/restore`,{method:'POST',body:'{}'});toast('备份已恢复');loadConfig()}catch(e){toast(e.message,true)}}
api('/api/auth/session').then(showApp).catch(showLogin);
